### ISSUE TITLE
代码块内输入冒号会引入 emoji

### ISSUE THREAD

**Issue by nks5117** [0xGG/crossnote-app#114]
如图，输入冒号后回车，就会自动填进去一个 emoji：
![2020-05-24_23-22-33](https://user-images.githubusercontent.com/33224777/82757981-5aea6000-9e16-11ea-9bb3-5abe551fe7ce.gif)

**Comment by shd101wyy** [comment]
恩我也发现有时候 `:` 并不好是，我可能会修改一下这个行为，谢谢啦

**Comment by shd101wyy** [comment]
@nks5117 应该是修好了，我现在设置了 emoji 的自动补全行为和 [autocomplete-emojis](https://atom.io/packages/autocomplete-emojis) 一样了。  

关于软件更新的化，你可以等浏览器弹出更新提醒，或者自己手动硬刷新网页。当然我推荐第一种更新方式。  

谢谢
