### ISSUE TITLE
Editor color scheme not respected in preview window

### ISSUE THREAD

**Issue by szmejap** [0xGG/crossnote-app#117]
Thank you for an excellent extension!

I encountered the following bug: preview window is not consistent in respecting the editor color scheme:

* When open using keyboard shortcut (Ctrl+K V) it follows the color scheme
* When open using right-click menu it uses the default bright scheme

![glitch md - Visual Studio Code 2020-06-02 11-57-40](https://user-images.githubusercontent.com/29229881/83507194-829d9000-a4c8-11ea-83cc-b64b475152ba.gif)

**Comment by shd101wyy** [comment]
Hi @szmejap , thanks, but you posted the issue in a wrong repository 😂.
You can change the preview theme in the extension settings. Search for `previewTheme` and you will find it. 
Seems like `Ctrl+K V` opens the default markdown preview, not the preview by MPE. The bright preview in your screenshot is the one by MPE.  
Thanks

**Comment by szmejap** [comment]
Ah, thank you for the response, and sorry for the confusion.
