### ISSUE TITLE
[Discussion] Should I make this project completely GitHub Pages based?

### ISSUE THREAD

**Issue by shd101wyy** [0xGG/crossnote-app#118]
This will remove cloud widgets support, such as the comment widget.  
Also, this will remove the explore and account system.

**Comment by aisbergde** [comment]
no, you should not. Github pages are only one per account and organization.
But it should be possible to use different repositories. How this should work with only one page per account and if this one page is used for other purposes, for example for a personal webpage?

Or did I misunderstood the idea?

**Comment by tgrrr** [comment]
Do you mean to limit the places to save markdown to github only, skipping other file syncing services @shd101wyy

**Comment by shd101wyy** [comment]
@tgrrr right now the build from `develop` branch is running on GitHub Pages. http://0xgg.github.io/crossnote
