### ISSUE TITLE
[Announcement][Discussion] Upcoming breaking changes

### ISSUE THREAD

**Issue by shd101wyy** [0xGG/crossnote-app#129]
I have been amazed by the RoamResearch and Obsidian recently. 
Therefore, I am planning to make some changes to the Crossnote:

1. [x] Remove the traditional file/directory tree view
2. [x] Remove the indefinitely nestable tags support 
3. [x] Remove the current `note` front-matter. Done in https://github.com/0xGG/crossnote/issues/126
4. [x] Support bidirectional links (backlinks, needs to support `Wikilink (MediaWiki syntax)` first)
5. [x] Support networking graph view
6. [ ] ~~Allow block level references (Check `@import` support by [MPE](https://github.com/shd101wyy/markdown-preview-enhanced))~~
6. [x] New UI Layout
etc

Please try it out at https://0xgg.io/crossnote/ :)
We will migrate it to https://crossnote.app when everything is ready.  

I will tag the current Crossnote as `beta-2`. I will move it to another repository, and make it completely host on GitHub Page.  
All the planned new features will belong to the `beta-3`.  

Feel free to leave your thoughts here. 

Thank you!

**Comment by yuanqiuye** [comment]
This application is awesome!
But maybe let the way of change note's folder become easily by add a new UI for it.  (When I change my folder for note, typing may have some mistake XD)
And if you have done all of your new features, add a markdown tool bar like this will let typing markdown on the phone more convenient!
![Screenshot_20200716_015844_com.github.android.jpg](https://user-images.githubusercontent.com/18190066/87579147-0f627d00-c708-11ea-9ae7-4c80ad7ff05c.jpg)

Thank you!

**Comment by awsomesawce** [comment]
Very interesting note taking app.  I found this app from a VSC extension.  This stands out from the other MD note-taking apps out there.  Lots of cool features.  Keep up the good work!

**Comment by fbob** [comment]
Excellent news !
You may be very interested  with the guys of Foam
https://foambubble.github.io/foam/
Perhaps you can join your effort or share some advancement together

**Comment by xukongwen** [comment]
我太爱这个了！等不及了！快快快！

**Comment by shd101wyy** [comment]
The new version is now officially released ;)

Closing this issue now 👍
