### ISSUE TITLE
Show tag counts

### ISSUE THREAD

**Issue by dougcooper** [0xGG/crossnote-app#148]
As a user I want to be able to see the number of instances of a tag. This helps me organize relationships between tagged notes. For instance if only one tag instance exists this may be an indicator of poor tagging or lack of information for a given note.

**Comment by shd101wyy** [comment]
I would say this feature is now supported in another way. The number of notes below the `References` section shows the number of notes related to this note (Now note == tag)

![Screenshot from 2021-03-16 00-31-27](https://user-images.githubusercontent.com/1908863/111187582-158a5f80-85ef-11eb-9242-1f7990a034ba.png)
