### ISSUE TITLE
Mac和Linux看不到不同的界面

### ISSUE THREAD

**Issue by wbgentleman** [0xGG/crossnote-app#15]
为什么在Mac的Chrome里面和Linux的Chrome里面看到界面不同呢？

**Comment by wbgentleman** [comment]
![image](https://user-images.githubusercontent.com/1073214/77603872-21979000-6f4c-11ea-9b9f-9c650f4b4174.png)
Linux Chrome看到的

**Comment by wbgentleman** [comment]
<img width="1289" alt="Screen Shot 2020-03-26 at 10 26 45 AM" src="https://user-images.githubusercontent.com/1073214/77604016-7509de00-6f4c-11ea-9a5a-35191ccac249.png">
MacChrome看到的界面

**Comment by shd101wyy** [comment]
@wbgentleman 是的昨天我进行了更新，下面的是最新的😂 建议 cmd-shift-r 硬刷新一下，然后右键审查元素，原则 Application 后清空下所有的 cache。

我今晚会更新下文档，因为变动很大
