### ISSUE TITLE
您好，是否能添加文章内目录功能

### ISSUE THREAD

**Issue by SkySoar-CN** [0xGG/crossnote-app#153]
我有一篇比较长的文章，我希望在文章开头的位置，添加目录指向各个章节。我尝试 `[目录1](#Head1)` 然而并不成功。
期待您的回复。

**Comment by SkySoar-CN** [comment]
另外还想指向其他文章的某个章节。

**Comment by shd101wyy** [comment]
你好。是的这个特性未来会支持的，现在还未支持。谢谢！

**Comment by StickChen** [comment]
我是没有侧边栏目录树感觉用不起来

**Comment by shd101wyy** [comment]
@lyunnashihou @StickChen 最新的版本支持文章内目录了 :)
