### ISSUE TITLE
建议: 打开笔记默认是编辑模式 而不是预览模式

### ISSUE THREAD

**Issue by ylsds** [0xGG/crossnote-app#155]
设置里能新增一个开关设置一下 打开笔记默认是预览模式,但是可以设置编辑模式吗

**Comment by shd101wyy** [comment]
最近没有开发这个项目，未来会支持的。谢谢 :)

**Comment by shd101wyy** [comment]
@ylsds 现在支持了。可以在设置中设置“默认编辑器模式”：

![EB8994FD-F498-43E6-AD27-E6FB4D7E5CD7](https://user-images.githubusercontent.com/1908863/109676736-f5e94500-7bb3-11eb-889e-4db4913edcd5.png)
