### ISSUE TITLE
想问下这张图是哪家店😏

### ISSUE THREAD

**Issue by LeoJhonSong** [0xGG/crossnote-app#21]
![image](https://user-images.githubusercontent.com/37630203/77730654-2e93ac80-703c-11ea-8c9c-de62bf15c69d.png)
如题:smirk:

老哥加油! 这个应用很棒啊! 尤其幻灯片功能很赞!

**Comment by shd101wyy** [comment]
咳咳好像是家羊蝎子店叫做 【蝎王府羊蝎子】

谢谢夸奖 🤓！项目还在持续开发中，预计一周内添加评论功能的支持 🙈。

**Comment by LeoJhonSong** [comment]
我有机会也去试试😋
