### ISSUE TITLE
希望敲代码的时候代码缩进能够和上行一致。

### ISSUE THREAD

**Issue by Robothy** [0xGG/crossnote-app#50]
![Crossnote 2020-04-20 22-05-19 mp4_20200420_220917](https://user-images.githubusercontent.com/10234260/79761279-cb075100-8353-11ea-908d-a159e1c00fa5.gif)

**Comment by shd101wyy** [comment]
这个貌似是 codemirror 的默认行为，我有时间去研究下。谢谢
