### ISSUE TITLE
使用Echarts如何声明变量或函数

### ISSUE THREAD

**Issue by feihuao** [0xGG/crossnote-app#63]
Diagrams中使用~~~Echarts实例中如果出现声明变量Var或函数function ()，请问如何处理，谢谢！
---
var colors = ['#5793f3', '#d14a61', '#675bba'];
option = {
    color: colors,
---
https://www.echartsjs.com/examples/zh/editor.html?c=multiple-y-axis
https://www.echartsjs.com/examples/zh/editor.html?c=line-draggable

**Comment by shd101wyy** [comment]
这个目前暂不支持。目前只能用 `json`。。。

**Comment by shd101wyy** [comment]
主要是因为运行 javascript 可能造成的安全因素。这块儿我还得花时间打磨打磨。🌝

**Comment by feihuao** [comment]
> 主要是因为运行 javascript 可能造成的安全因素。这块儿我还得花时间打磨打磨。🌝

非常期待！！reveal.js结合echarts进行交互式演示。
