### ISSUE TITLE
[GraphQL] invalid language error on editing profile.

### ISSUE THREAD

**Issue by nauman-chaudhary** [0xGG/crossnote-app#8]
![Screenshot from 2020-02-26 16-08-57](https://user-images.githubusercontent.com/13278766/75339719-e3f30900-58b2-11ea-98e8-97ed867379cd.png)
After signup I tried to change my cover and avatar.
When I save it this error shows on top right corner and then nothing happens.

**Comment by shd101wyy** [comment]
Hi there. The issue should be fixed now. Thanks ;)

However, I might stop maintaining this project. I am planning to open source everything by the end of March.

Thank you

**Comment by shd101wyy** [comment]
Open sourced and the project has changed a lot. Thank you.
