### ISSUE TITLE
Local images not displayed 

### ISSUE THREAD

**Issue by NightMachinery** [0xGG/crossnote-app#87]
`![](media/15890405860934.png) ` doesn’t work. Note that media is in the directory of the markdown file, not repo’s root. (Haven’t tested putting it on the root.)

As imgur etc will take away the control of my files, this is a dealbreaker for me.

**Comment by shd101wyy** [comment]
Is that git repository public so I can try it on Crossnote? Thank you

**Comment by NightMachinery** [comment]
@shd101wyy It’s not, unfortunately. I do have another one that uses local images at https://github.com/batbone/stochastic/blob/master/coronavirus/model.md but I haven’t tested it.

**Comment by shd101wyy** [comment]
Hi @NightMachinary , the issue should be fixed now in commit [06a50e](https://github.com/0xGG/crossnote/commit/06a50ee85191018342d82284b28c125e923ec5ac). 
You can either do a hard refresh in your browser or wait for the update notification popping up in Crossnote to update.    
Thank you
