### ISSUE TITLE
Please include separate live like in vscode

### ISSUE THREAD

**Issue by parthi2929** [0xGG/crossnote-app#98]
Hi

This is cool, I am excited to use this, however, it would be really useful if I have editing and preview separated (especially in long formula & graphs via puml etc).. can you please provide that option?

**Comment by shd101wyy** [comment]
Yeah it’s possible. Will be planned. Thanks

**Comment by parthi2929** [comment]
thanks for super fast reply.. also can it be wrapped in electron? Currently having to open browser, and then chrome apps and then click on it to launch it..

**Comment by shd101wyy** [comment]
Unfortunately, crossnote.app is meant to be built as a progressive web application. 
Once you install it by Chrome, it runs offline. 

![Screenshot from 2020-05-13 18-58-54](https://user-images.githubusercontent.com/1908863/81804517-d06b4c00-954b-11ea-8b7c-eaa0181e98d3.png)

I personally added it to my dock after installing from Chrome.  
  
If you want to try the completely offline one, this vscode extension might be what you want: https://github.com/0xGG/crossnote. But it currently misses some features that the web version has.

Thanks

**Comment by shd101wyy** [comment]
Done. The split view is supported now.
You can either hard refresh your browser or wait for the update notification popping up to get updates.

**Comment by parthi2929** [comment]
That is great. Thanks.
